# Generated by Django 5.0.4 on 2024-04-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
