# Generated by Django 5.0.4 on 2024-04-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_event_lancers_three_event_lancers_two_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermoney",
            name="money",
            field=models.FloatField(default=100),
        ),
    ]
